betAdmin/core/urls.py
from django.urls import path
from betAdmin.core import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index')
]

betAdmin/payments/urls.py
from django.urls import path
from betAdmin.payments.views import PaymentView, PaymentViewUpdated, PaymentViewDelete, AdministratorAccountView

app_name = 'payments'

urlpatterns = [
    path('sign_plan/', PaymentView.as_view(), name='sign_plan'),
    path('sign_plan/<int:pk>/update', PaymentViewUpdated.as_view(), name='sign_plan_updated'),
    path('sign_plan/<int:pk>/delete', PaymentViewDelete.as_view(), name='sign_plan_delete'),
    path('administrator-account/<int:pk>', AdministratorAccountView.as_view(), name='administrator_account'),
]

betAdmin/queries/urls.py
from django.urls import path
from betAdmin.queries import views

app_name = 'queries'

urlpatterns = [
    path('statement/', views.index, name='queries')
]

betAdmin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    path('', include('betAdmin.core.urls', namespace='core')),
    path('payments/', include('betAdmin.payments.urls', namespace='payments')),
    path('accounts/', include('betAdmin.accounts.urls', namespace='accounts')),
    path('queries/', include('betAdmin.queries.urls', namespace='queries')),
    path('admin/', admin.site.urls),

    path('api/v1/', include('betAdmin.accounts.api.urls')),
    path('api/v1/', include('betAdmin.payments.api.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

betAdmin/core/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Event(models.Model):
    match = models.ForeignKey('Match', on_delete=models.CASCADE, related_name="events")
    param = models.ForeignKey('Param', on_delete=models.CASCADE, related_name="events")
    value = models.IntegerField()
    period = models.CharField(max_length=255)
    time = models.IntegerField(blank=True, null=True)
    team = models.BooleanField()

    class Meta:
        db_table = 'event'
        ordering = ['param']
        

class Match(models.Model):
    global_match_id = models.IntegerField(unique=True)
    date = models.DateTimeField()
    home_team_fk = models.ForeignKey('Team', on_delete=models.CASCADE, related_name="home_matchs")
    away_team_fk = models.ForeignKey('Team', on_delete=models.CASCADE, related_name="away_matchs")
    score_home_team = models.IntegerField(blank=True, null=True)
    score_away_team = models.IntegerField(blank=True, null=True)
    winner = models.CharField(max_length=255, blank=True, null=True)
    tournament = models.ForeignKey('Tournament', on_delete=models.CASCADE, related_name="matchs", blank=True, null=True)
    country = models.CharField(max_length=255, blank=True, null=True)
    archived = models.DateTimeField(blank=True, null=True)

    class Meta:
        db_table = 'match'
        ordering = ['tournament']
    
    def __str__(self):
        return str(self.global_match_id)


class Param(models.Model):
    name = models.CharField(max_length=255)
    label = models.CharField(max_length=255)
    note = models.TextField()

    class Meta:
        db_table = 'param'
        ordering = ['name']

    def __str__(self):
        return self.name


class Team(models.Model):
    global_team_id = models.IntegerField()
    name = models.CharField(max_length=255)

    class Meta:
        db_table = 'team'
        ordering = ['name']

    def __str__(self):
        return self.name


class Tournament(models.Model):
    global_tournament_id = models.IntegerField()
    name = models.CharField(max_length=255)

    class Meta:
        db_table = 'tournament'
        ordering = ['name']

    def __str__(self):
        return self.name

betAdmin/core/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Create your views here.
from betAdmin.payments.models import Payment


@login_required()
def index(request):
    template_name = 'index.html'

    payment = Payment()

    context = {
        'payment': payment.active_payment(request.user)
    }
    return render(request, template_name, context)

core/views/core.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Create your views here.

@login_required()
def index(request):
    template_name = 'core/index.html'
    context = {

    }
    return render(request, template_name,context)

betAdmin/core/templates/index.html
{% extends 'components/page.html' %}

{% block page-container %}

    <div class="ui grid container main-container">

        <div class="four wide column mobile hidden tablet hidden">
            <div class="ui vertical menu large">
                <div class="item">
                    <div class="header">Base de Conhecimento</div>
                    <div class="menu">
                        <a class="item" href="{% url 'queries:queries' %}">Dados Futebol</a>
                    </div>
                </div>
                <div class="item">
                    <div class="header">Plano</div>
                    <div class="menu">
                        <a class="item" href="{% url 'payments:sign_plan' %}">
                            {% if payment %}
                                Renovar Plano
                            {% else %}
                                Assinar Plano
                            {% endif %}
                        </a>
                        <a class="item">Validade: {{ payment.expiration_date }}</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="twelve wide computer sixteen wide tablet column">
            <div class="ui main segment">

                <!--
                <h1 class="ui header">Semantic UI Fixed Template</h1>
                <p>This is a basic fixed menu template using fixed size containers.</p>
                <p>A text container is used for the main container, which is useful for single column layouts</p>
                -->

                {% block main-container %}
                {% endblock %}

            </div>
        </div>
    </div>

{% endblock %}