betAdmin/accounts/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from betAdmin.accounts.api.viewsets import SimpleProfileViewSet

router_viewsets = DefaultRouter()
router_viewsets.register(r'profiles/simple', SimpleProfileViewSet, basename='simple_profile')

from betAdmin.accounts.api.apiviews import UserAPIView


urlpatterns = [
    path('', include(router_viewsets.urls)),
    path('logout', UserAPIView.as_view()),
    path('token', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh', TokenRefreshView.as_view(), name='token_refresh'),
]

betAdmin/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from betAdmin.accounts import views as account_views

app_name = 'accounts'

urlpatterns = [
    path('login/',
         auth_views.LoginView.as_view(template_name='login.html',
                                      redirect_authenticated_user=True),
         name='login'),

    path('signup/', account_views.register, name='signup'),

    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('profile/', account_views.profile, name='profile'),

    path('resend_email/', account_views.resend_email, name='resend_email'),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(
             template_name='passowrd_reset.html',
             email_template_name='password_reset_email.html',
             success_url=reverse_lazy('accounts:password_reset_done')
         ),
         name='password_reset'),

    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='password_reset_done.html'
         ),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='password_reset_confirm.html',
             success_url=reverse_lazy('accounts:login')
         ),
         name='password_reset_confirm'),

    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        account_views.activate, name='activate'),
]

betAdmin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    path('', include('betAdmin.core.urls', namespace='core')),
    path('payments/', include('betAdmin.payments.urls', namespace='payments')),
    path('accounts/', include('betAdmin.accounts.urls', namespace='accounts')),
    path('queries/', include('betAdmin.queries.urls', namespace='queries')),
    path('admin/', admin.site.urls),

    path('api/v1/', include('betAdmin.accounts.api.urls')),
    path('api/v1/', include('betAdmin.payments.api.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

betAdmin/accounts/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(User):

    phone = models.CharField(max_length=20, blank=True, null=True)
    country = models.CharField(max_length=20, blank=True, null=True)
    city = models.CharField(max_length=20, blank=True, null=True)
    zip_code = models.CharField(max_length=20, blank=True, null=True)
    street_address = models.CharField(max_length=50, blank=True, null=True)    
    uf = models.CharField(max_length=2, blank=True, null=True)    
    number = models.CharField(max_length=5, blank=True, null=True)    
    email_confirmed = models.BooleanField(default=False)


class Query(models.Model):

    name = models.CharField(max_length=50)
    query = models.CharField(max_length=250)
    profile = models.ForeignKey(Profile, related_name='query', on_delete=models.CASCADE)

betAdmin/accounts/forms/registration.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from betAdmin.accounts.tokens import account_activation_token
from betAdmin.core.mail import send_mail_template
from betAdmin.accounts.models import Profile


class RegistrationForm(UserCreationForm):

    email = forms.EmailField(label='E-mail', widget=forms.TextInput(attrs={'placeholder': 'E-mail'}))

    class Meta:
        model = Profile
        fields = ("username",)
        field_classes = {'username': UsernameField}

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Este e-mail já existe está cadastrado.')
        return email

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
                
        if commit:
            user.save()
        return user

    def send_mail(self, user, request):
        subject = 'Link de Ativação de Conta'
        current_site = get_current_site(request)

        message = {
            'user': user, 'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': account_activation_token.make_token(user),
        }

        template_name = 'acc_active_email.html'

        send_mail_template(
            subject, template_name, message, ['caetanov120@gmail.com']
        )


class EditAccountForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'username', 'email', 
        'phone', 'country', 'city', 'zip_code', 'street_address',
        'uf', 'number']
        widgets = {
            'first_name' : forms.TextInput(attrs = {'placeholder': 'Prirmeiro nome'}),
            'last_name' : forms.TextInput(attrs = {'placeholder': 'Segundo nome'}),
            'phone' : forms.TextInput(attrs = {'placeholder': 'Telefone'}),
            'country' : forms.TextInput(attrs = {'placeholder': 'Pais'}),
            'city' : forms.TextInput(attrs = {'placeholder': 'Cidade'}),
            'zip_code' : forms.TextInput(attrs = {'placeholder': 'CEP'}),
            'street_address' : forms.TextInput(attrs = {'placeholder': 'Logradouro'}),
            'uf' : forms.TextInput(attrs = {'placeholder': 'UF'}),
            'number' : forms.TextInput(attrs = {'placeholder': 'Número'}),
        }

betAdmin/accounts/views.py
from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode

from betAdmin.accounts.forms.registration import RegistrationForm, EditAccountForm
from betAdmin.accounts.tokens import account_activation_token
from betAdmin.payments.models import Payment


def register(request):
    template_name = 'signup.html'

    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            email = RegistrationForm()
            email.send_mail(user, request)
            return redirect(settings.LOGIN_URL)

    else:
        form = RegistrationForm()

    context = {
        'form': form
    }

    return render(request, template_name, context)


@login_required()
def profile(request):
    template_name = 'profile.html'

    payments = Payment.objects.filter(user=request.user)

    context = { 'payments' : payments}
    if request.method == 'POST':
        form = EditAccountForm(request.POST,instance=request.user.profile)
        if form.is_valid():
            form.save()
            context['success'] = {
                'header' : 'Atualização',
                'content' : '{0} atualizado com sucesso!'.format(request.user)
            }
    else:
        form = EditAccountForm(instance=request.user.profile)

    context['form'] = form

    return render(request, template_name, context)


@login_required()
def resend_email(request):
    email = RegistrationForm()
    email.send_mail(request.user, request)
    return redirect(request.META.get('HTTP_REFERER'))


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token) and not user.profile.email_confirmed:
        user.profile.email_confirmed = True
        user.profile.save()
        login(request, user)
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')

betAdmin/accounts/templates/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

betAdmin/accounts/templates/login.html
{% extends 'components/base.html' %} {% block container %}
<div class="ui middle aligned center aligned grid">
    <div class="column" style="max-width: 450px;">

        <h2 class="ui grey image header">
            <img src="https://image.flaticon.com/icons/svg/1901/1901742.svg" class="image">
            <div class="content">
                Entre com suas credenciais
            </div>
        </h2>

        <form class="ui large form" method="post">
            {% csrf_token %}
            <div class="ui segment">

                <div class="field">
                    <label style="float: left;">{{ form.username.label }}</label>
                    <div class="ui left icon input">
                        <i class="user icon"></i> {{ form.username }}
                    </div>
                </div>

                <div class="field">
                    <label style="float: left;">{{ form.password.label }}</label>
                    <div class="ui left icon input">
                        <i class="lock icon"></i> {{ form.password }}
                    </div>
                </div>

                <button type="submit" class="ui fluid large blue submit button">Entrar</button>
            </div>
            <div class="ui error {% if form.non_field_errors %} visible {% endif %} message">{{ form.non_field_errors }}</div>
        </form>

        <div class="ui message">
            Não possui conta? <a href="{% url 'accounts:signup' %}">Cadastre-se</a> <br> Esqueceu senha? <a href="{% url 'accounts:password_reset' %}">Recupere</a>
        </div>

    </div>
</div>

{% endblock %}

betAdmin/accounts/templates/passowrd_reset.html
{% extends 'components/base.html' %} {% block container %}
<div class="ui middle aligned center aligned grid">
    <div class="column">

        <h2 class="ui grey image header">
            <img src="https://image.flaticon.com/icons/svg/1901/1901742.svg" class="image">
            <div class="content">
                Recuperação de Senha
            </div>
        </h2>

        <form class="ui large form" method="post">
            {% csrf_token %}
            <div class="ui segment">
                {% for field in form %}
                <div class="field">
                    <label style="float: left;">{{ field.label }}</label>
                    <div class="ui left icon input">
                        <i class="user icon"></i> {{ field }}
                    </div>
                </div>
                {% endfor %}
                <button type="submit" class="ui fluid large blue submit button">Entrar</button>
            </div>
            <div class="ui error {% if form.non_field_errors %} visible {% endif %} message">{{ form.non_field_errors }}</div>
        </form>
        <div class="ui message">
            Já possui cadastro? <a href="{% url 'accounts:login' %}">Entre</a>
        </div>
    </div>
</div>
{% endblock %}

betAdmin/accounts/templates/password_reset_confirm.html
<!-- Form where user changer its password-->
<form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Change password</button>
</form>

betAdmin/accounts/templates/password_reset_done.html
Voce irá recebel no seu email

betAdmin/accounts/templates/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

betAdmin/accounts/templates/profile.html
{% extends 'components/page.html' %} {% block page-container %}

    <div class="ui container text segment">

        <div class="ui top attached tabular menu">
            <div class="item" data-tab="first">Informações Pessoais</div>
            <div class="active item" data-tab="second">Financeiro</div>
            <div class="item" data-tab="third">Registros</div>
            <div class="item" data-tab="fourth">Conta</div>
        </div>
        <div class="ui bottom attached tab segment" data-tab="first">
            <form class="ui form" method="POST">
                {% csrf_token %}
                <div class="field">
                    <label>Name</label>
                    <div class="two fields">
                        <div class="field">
                            {{ form.first_name.errors }} {{ form.first_name }}
                        </div>
                        <div class="field">
                            {{ form.last_name.errors }} {{ form.last_name }}
                        </div>
                    </div>
                </div>

                <div class="field">
                    <label>Conta</label>
                    <div class="two fields">
                        <div class="field">
                            {{ form.username.errors }} {{ form.username }}
                        </div>
                        <div class="field">
                            {{ form.email.errors }} {{ form.email }}
                        </div>
                    </div>
                </div>

                <h4 class="ui dividing header"></h4>

                <div class="field">
                    <label>Endereço</label>
                    <div class="two fields">
                        <div class="four wide field">
                            {{ form.zip_code.errors }} {{ form.zip_code }}
                        </div>
                        <div class="twelve wide field">
                            {{ form.street_address.errors }} {{ form.street_address }}
                        </div>
                    </div>
                    <div class="two fields">
                        <div class="four wide field">
                            {{ form.number.errors }} {{ form.number }}
                        </div>
                        <div class="four wide field">
                            {{ form.city.errors }} {{ form.city }}
                        </div>
                        <div class="four wide field">
                            {{ form.uf.errors }} {{ form.uf }}
                        </div>
                        <div class="four wide field">
                            {{ form.country.errors }} {{ form.country }}
                        </div>
                    </div>
                </div>

                <h4 class="ui dividing header"></h4>

                <div class="field">
                    <label>Contato</label>
                    <div class="two fields">
                        <div class="four wide field">
                            {{ form.phone.errors }} {{ form.phone }}
                        </div>
                    </div>
                </div>

                <button type="submit" class="ui blue submit button">Salvar</button>
            </form>
        </div>

        <div class="ui bottom attached active  tab segment" data-tab="second">

            <table class="ui celled table">
                <thead>
                <tr>
                    <th>Pagamento</th>
                    <th>Vencimento</th>
                    <th>Valor</th>
                    <th>Situação</th>
                    <th>Arquivo</th>
                </tr>
                </thead>
                <tbody>
                {% for payment in payments %}
                    <tr>
                        <td data-label="Age">{{ payment.payment_date |default_if_none:"-" }}</td>
                        <td data-label="Age">{{ payment.expiration_date |default_if_none:"-" }}</td>
                        <td data-label="Age">{{ payment.value }}</td>
                        {% if  payment.is_paid %}
                            <td data-label="Age">Pago</td>
                        {% else %}
                            <td data-label="Age">Pendente</td>
                        {% endif %}
                        <td data-label="Age">{{ '' }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
        <div class="ui bottom attached tab segment" data-tab="third">
            <p>Registros</p>
        </div>
        <div class="ui bottom attached tab segment" data-tab="fourth">
            <p>Conta</p>
        </div>

    </div>

{% endblock %}

betAdmin/accounts/templates/signup.html
{% extends 'components/base.html' %} {% block container %}

<div class="ui middle aligned center aligned grid">
    <div class="column">

        <h2 class="ui grey image header">
            <img src="https://image.flaticon.com/icons/svg/1901/1901742.svg" class="image">
            <div class="content">
                Crie sua conta
            </div>
        </h2>

        <form class="ui large form" method="POST">
            {% csrf_token %}
            <div class="ui segment">

                <div class="field">
                    {% include 'component/field.html' with item=form.username icon='user' %}
                </div>

                <div class="field">
                    {% include 'component/field.html' with item=form.email icon='envelope' %}
                </div>

                <div class="field">
                    <div class="two fields">
                        <div class="field">
                            {% include 'component/field.html' with item=form.password1 icon='lock' %}
                        </div>
                        <div class="field">
                            {% include 'component/field.html' with item=form.password2 icon='lock' %}
                        </div>
                    </div>
                </div>

                <button type="submit" class="ui fluid large blue button">Cadastrar</button>
            </div>
        </form>

        <div class="ui message">
            Já possui cadastro? <a href="{% url 'accounts:login' %}">Entre</a>
        </div>

    </div>
</div>

{% endblock %}