betAdmin/payments/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from betAdmin.payments.api.viewsets import AdministratorAccountViewSet, PlanViewSet

router_viewsets = DefaultRouter()
router_viewsets.register('accounts/administrator', AdministratorAccountViewSet, basename='administrator_account')
router_viewsets.register('accounts/plans', PlanViewSet, basename='administrator_account')


urlpatterns = [
    path('', include(router_viewsets.urls)),
]

betAdmin/payments/urls.py
from django.urls import path
from betAdmin.payments.views import PaymentView, PaymentViewUpdated, PaymentViewDelete, AdministratorAccountView

app_name = 'payments'

urlpatterns = [
    path('sign_plan/', PaymentView.as_view(), name='sign_plan'),
    path('sign_plan/<int:pk>/update', PaymentViewUpdated.as_view(), name='sign_plan_updated'),
    path('sign_plan/<int:pk>/delete', PaymentViewDelete.as_view(), name='sign_plan_delete'),
    path('administrator-account/<int:pk>', AdministratorAccountView.as_view(), name='administrator_account'),
]

betAdmin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    path('', include('betAdmin.core.urls', namespace='core')),
    path('payments/', include('betAdmin.payments.urls', namespace='payments')),
    path('accounts/', include('betAdmin.accounts.urls', namespace='accounts')),
    path('queries/', include('betAdmin.queries.urls', namespace='queries')),
    path('admin/', admin.site.urls),

    path('api/v1/', include('betAdmin.accounts.api.urls')),
    path('api/v1/', include('betAdmin.payments.api.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

betAdmin/payments/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User


class AdministratorAccount(models.Model):
    CHECKING_ACCOUNT = 'CC'
    SAVINGS_ACCOUNT = 'CP'
    ACCOUNT_CHOICES = [
        (CHECKING_ACCOUNT, 'checking account'),
        (SAVINGS_ACCOUNT, 'savings account'),
    ]

    name = models.CharField(max_length=50)
    bank_name = models.CharField(max_length=50, null=True)
    bank_number = models.CharField(max_length=10, null=True)
    agency = models.CharField(max_length=10)
    account_number = models.CharField(max_length=10)
    digit = models.CharField(max_length=2)
    op = models.CharField(max_length=5)
    account_type = models.CharField(max_length=2, choices=ACCOUNT_CHOICES, default=SAVINGS_ACCOUNT)
    is_active = models.BooleanField(default=True)

    class Meta:
        db_table = 'payments_administrator_account'

    def __str__(self):
        return self.name


class Plan(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=250)
    day = models.IntegerField()
    price = models.FloatField()

    class Meta:
        db_table = 'payments_plan'

    def __str__(self):
        return self.name


class Payment(models.Model):
    CREDIT_CARD = 'CC'
    TICKET = 'TK'
    TRANSFER = 'TR'
    DEPOSIT = 'DP'
    PAYMENT_CHOICES = [
        (CREDIT_CARD, 'credit card'),
        (TICKET, 'ticket'),
        (TRANSFER, 'transfer'),
        (DEPOSIT, 'deposit'),
    ]

    def payment_directory_path(instance, filename):
        # file will be uploaded to MEDIA_ROOT/payments/user_<id>/<filename>
        return 'payments/{0}/{1}'.format(instance.user.id, filename)

    payment_date = models.DateField(auto_now=False, auto_now_add=False, null=True)
    expiration_date = models.DateField(auto_now=False, auto_now_add=False, null=True)
    payment_method = models.CharField(max_length=2, choices=PAYMENT_CHOICES, default=TRANSFER)
    is_paid = models.BooleanField(default=False)
    file = models.FileField(upload_to=payment_directory_path, max_length=100, blank=True, null=True)
    user = models.ForeignKey(User, related_name='payments_user', on_delete=models.CASCADE)
    adm_account = models.ForeignKey(AdministratorAccount, related_name='payments_adm_account', on_delete=models.CASCADE)
    plan = models.ForeignKey(Plan, related_name='payments', on_delete=models.CASCADE)

    def active_payment(self, user):
        payment = Payment.objects.filter(user=user).filter(is_paid=True).order_by('expiration_date').reverse().first()
        try:
            if payment.expiration_date >= datetime.datetime.today().date():
                return payment
            else:
                return None
        except:
            return None

    def pendent_payment(self, user):
        payment = Payment.objects.filter(user=user).filter(is_paid=False).first()
        if payment:
            return payment
        else:
            return False

    def __str__(self):
        return self.user.username

betAdmin/payments/forms/payments.py
from django import forms

from betAdmin.payments.models import Payment, AdministratorAccount, Plan

class SavePaymentForm(forms.ModelForm):

    class Meta:
        model = Payment
        fields = ['payment_method', 'adm_account', 'plan','file']
        file = forms.FileField(required = False)
        widgets = {
            'payment_method' : forms.Select(choices=Payment.PAYMENT_CHOICES, attrs = {'placeholder': 'Método de pagamento'}),
            'plan' : forms.Select(choices=Payment.PAYMENT_CHOICES, attrs = {'placeholder': 'Selecione o tipo de plano'}),
            'adm_account' : forms.Select(choices=AdministratorAccount.CHECKING_ACCOUNT, attrs = {'placeholder': 'Selecione a conta', 'onchange':"changeAccountPayment(this)"}),
        }

betAdmin/payments/views.py
import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.views import View
from django.forms.models import model_to_dict

from betAdmin.payments.models import AdministratorAccount, Plan, Payment
from betAdmin.payments.forms.payments import SavePaymentForm
from dateutil.relativedelta import *


class PaymentView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        template_name = 'sign_plan.html'

        payment = Payment()

        payment_pendent = payment.pendent_payment(request.user)

        payment_instance = payment_pendent if payment_pendent else None

        context = {
            'payment_pendent': payment_pendent,
            'payment_active': payment.active_payment(request.user),
            'form' : SavePaymentForm(instance=payment_instance)
        }

        return render(request, template_name, context)

    def post(self, request, *args, **kwargs):
        template_name = 'sign_plan.html'

        context = {}
        payment_form = SavePaymentForm(request.POST)
        payment_form.instance.user_id = request.user.pk
        payment_form.instance.payment_date = datetime.datetime.today().date()

        if payment_form.is_valid():
            active = payment_form.instance.active_payment(request.user)
            if active:
                payment_form.instance.expiration_date = active.expiration_date + relativedelta(months=payment_form.instance.plan.day)
            else:
                payment_form.instance.expiration_date = datetime.datetime.today() + relativedelta(months=payment_form.instance.plan.day)
        
            payment_form.save()
         
            return HttpResponseRedirect(reverse('payments:sign_plan'))

        return render(request, template_name, context)


class PaymentViewUpdated(LoginRequiredMixin, View):
    
    def post(self, request, pk, *args, **kwargs):
        template_name = "sign_plan.html"
        payment = Payment.objects.get(pk=pk)
        if request.FILES.get('file'):
            payment.file = request.FILES['file']
        payment.save()
        return HttpResponseRedirect(reverse('payments:sign_plan'))


class PaymentViewDelete(LoginRequiredMixin, View):
    
    def post(self, request, pk, *args, **kwargs):
        payment = Payment.objects.get(pk=pk)
        payment.delete()
        return HttpResponseRedirect(reverse('payments:sign_plan'))


class AdministratorAccountView(LoginRequiredMixin, View):

    def get(self, request, pk):
        try:
            account = AdministratorAccount.objects.get(pk=pk)
            data = model_to_dict(account)
            return JsonResponse(data)
        except Exception as e:
            return JsonResponse({"wew":str(e)})

betAdmin/payments/templates/account_data.html
<div class="ui container">
    <div class="ui two column centered grid">
        <div class="four column centered row">
            <div class="column">
                <h2 class="ui center aligned icon header">
                    Conta<i class="circular dollar sign icon"></i>
                </h2>
            </div>
            <div class="column">
                <div class="ui list">
                    <div class="item">
                        <i class="user icon"></i>
                        <div class="content">
                            Favorecido:<span id="name"></span>
                        </div>
                    </div>
                    <div class="item">
                        <i class="th icon"></i>
                        <div class="content">
                            Banco: <span id="bank_name"></span>
                        </div>
                    </div>
                    <div class="item">
                        <i class="mail icon"></i>
                        <div class="content">
                            Agencia: <span id="agency"></span>
                        </div>
                    </div>
                    <div class="item">
                        <i class="address card icon"></i>
                        <div class="content">
                            Conta: <span id="account_number"></span> - <span id="digit"></span>
                        </div>
                    </div>
                    <div class="item">
                        <i class="keyboard icon"></i>
                        <div class="content">
                            Operação: <span id="op"></span>
                        </div>
                    </div>
                    <div class="item">
                        <i class="file code outline icon"></i>
                        <div class="content">
                            Tipo: <span id="account_type"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

betAdmin/payments/templates/sign_plan.html
{% extends 'components/page.html' %} {% block page-container %}
<div class="ui container segment">

    {% if payment_pendent %}

    <div class="ui warning message">
        <div class="header">
            Você possui um pagamento pendente
        </div>
        Pagamentos demoram até 72h para serem processados. É importante anexar o comprovante após pagamento.
    </div>

    {% endif %} {% if not payment_pendent %}

    <form class="ui form" method="post">
        {% csrf_token %}
        <h4 class="ui dividing header">Plano de Assinatura</h4>
        <div class="fields">
            <div class="eight wide field">
                {{form.plan.label}}{{ form.plan }}
            </div>
            <div class="eight wide field">
                {{form.adm_account.label}} {{ form.adm_account }}
            </div>
            <div class="eight wide field">
                {{ form.payment_method.label }} {{ form.payment_method }}
            </div>
        </div>
        <button type="submit" class="ui blue submit button">Assinar</button>
    </form>

    {% include "account_data.html" %} {% else %}

    <table class="ui celled table">
        <thead>
            <tr>
                <th>Cód.</th>
                <th>Pagamento</th>
                <th>Vencimento</th>
                <th>Valor</th>
                <th>Situação</th>
                <th>
                    Arquivo
                </th>
                {% if not payment_pendent.file %}
                <th>Excluir</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            <tr>
                <td data-label="Age">{{ payment_pendent.id }}</td>
                <td data-label="Age">{{ payment_pendent.payment_date |default_if_none:"-" }}</td>
                <td data-label="Age">{{ payment_pendent.expiration_date |default_if_none:"-" }}</td>
                <td data-label="Age">{{ payment_pendent.plan.price }}</td>
                <td data-label="Age">
                    {% if payment_pendent.is_paid %}Pago {% else %} Pendente {% endif %}
                </td>
                <td data-label="Age" class="center aligned">
                    {% if payment_pendent.file %}
                    <a href='{{payment_pendent.file.url}}' target='_blank' class="href">
                        <i class=" file alternate outline icon"></i>
                    </a>
                    {% endif %}
                </td>
                {% if not payment_pendent.file %}
                <td data-label="Age" class="center aligned">
                    <form action="{% url 'payments:sign_plan_delete' pk=payment_pendent.id%}" method="POST">
                        {% csrf_token %}
                        <a href="#" onclick="deleteSignPlan('{{payment_pendent.id}}',this)">
                            <i class=" trash alternate outline icon red "></i>
                        </a>
                    </form>
                </td>
                {% endif %}
            </tr>
        </tbody>
    </table>
    {% if not payment_pendent.file %}
    <form action="{% url 'payments:sign_plan_updated' pk=payment_pendent.id %}" class="ui form" method="POST" enctype="multipart/form-data">
        <div class="eight wide field">
            {% csrf_token %} {{form.file}}
        </div>
        <button type="submit" class="ui blue submit button">Atualizar</button>
    </form>
    {% endif %}
    <p>* Anexe o comprovante de depósito e aguarde o período necessário. Em caso de dúvidas entre em contato.
    </p>

    {% endif %}

</div>

{% endblock %}