betAdmin/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from betAdmin.accounts import views as account_views

app_name = 'accounts'

urlpatterns = [
    path('login/',
         auth_views.LoginView.as_view(template_name='login.html',
                                      redirect_authenticated_user=True),
         name='login'),

    path('signup/', account_views.register, name='signup'),

    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('profile/', account_views.profile, name='profile'),

    path('resend_email/', account_views.resend_email, name='resend_email'),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(
             template_name='passowrd_reset.html',
             email_template_name='password_reset_email.html',
             success_url=reverse_lazy('accounts:password_reset_done')
         ),
         name='password_reset'),

    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='password_reset_done.html'
         ),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='password_reset_confirm.html',
             success_url=reverse_lazy('accounts:login')
         ),
         name='password_reset_confirm'),

    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        account_views.activate, name='activate'),
]

betAdmin/core/urls.py
from django.urls import path
from betAdmin.core import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index')
]

betAdmin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    path('', include('betAdmin.core.urls', namespace='core')),
    path('payments/', include('betAdmin.payments.urls', namespace='payments')),
    path('accounts/', include('betAdmin.accounts.urls', namespace='accounts')),
    path('queries/', include('betAdmin.queries.urls', namespace='queries')),
    path('admin/', admin.site.urls),

    path('api/v1/', include('betAdmin.accounts.api.urls')),
    path('api/v1/', include('betAdmin.payments.api.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

betAdmin/core/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Event(models.Model):
    match = models.ForeignKey('Match', on_delete=models.CASCADE, related_name="events")
    param = models.ForeignKey('Param', on_delete=models.CASCADE, related_name="events")
    value = models.IntegerField()
    period = models.CharField(max_length=255)
    time = models.IntegerField(blank=True, null=True)
    team = models.BooleanField()

    class Meta:
        db_table = 'event'
        ordering = ['param']
        

class Match(models.Model):
    global_match_id = models.IntegerField(unique=True)
    date = models.DateTimeField()
    home_team_fk = models.ForeignKey('Team', on_delete=models.CASCADE, related_name="home_matchs")
    away_team_fk = models.ForeignKey('Team', on_delete=models.CASCADE, related_name="away_matchs")
    score_home_team = models.IntegerField(blank=True, null=True)
    score_away_team = models.IntegerField(blank=True, null=True)
    winner = models.CharField(max_length=255, blank=True, null=True)
    tournament = models.ForeignKey('Tournament', on_delete=models.CASCADE, related_name="matchs", blank=True, null=True)
    country = models.CharField(max_length=255, blank=True, null=True)
    archived = models.DateTimeField(blank=True, null=True)

    class Meta:
        db_table = 'match'
        ordering = ['tournament']
    
    def __str__(self):
        return str(self.global_match_id)


class Param(models.Model):
    name = models.CharField(max_length=255)
    label = models.CharField(max_length=255)
    note = models.TextField()

    class Meta:
        db_table = 'param'
        ordering = ['name']

    def __str__(self):
        return self.name


class Team(models.Model):
    global_team_id = models.IntegerField()
    name = models.CharField(max_length=255)

    class Meta:
        db_table = 'team'
        ordering = ['name']

    def __str__(self):
        return self.name


class Tournament(models.Model):
    global_tournament_id = models.IntegerField()
    name = models.CharField(max_length=255)

    class Meta:
        db_table = 'tournament'
        ordering = ['name']

    def __str__(self):
        return self.name

betAdmin/core/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Create your views here.
from betAdmin.payments.models import Payment


@login_required()
def index(request):
    template_name = 'index.html'

    payment = Payment()

    context = {
        'payment': payment.active_payment(request.user)
    }
    return render(request, template_name, context)

core/views/core.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Create your views here.

@login_required()
def index(request):
    template_name = 'core/index.html'
    context = {

    }
    return render(request, template_name,context)

betAdmin/core/templates/components/base.html
{% load static %}
<!DOCTYPE html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>Bet Admin</title>
    <link rel="stylesheet" href="{% static 'Semantic-UI-CSS-2.4.1/semantic.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/body-custom.css' %}">

    <script src=" {% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src=" {% static 'Semantic-UI-CSS-2.4.1/semantic.min.js' %}"></script>
    <script src=" {% static 'js/init-functions-semantic.js' %}"></script>
    <script src=" {% static 'js/signPlan/functions.js' %}"></script>
</head>

<body>
    {% block container %} {% endblock %}
</body>

</html>

betAdmin/core/templates/components/page.html
{% extends 'components/base.html' %} {% block container %}

<div class="ui menu">
    <div class="ui container main-menu">
        <a href="{% url 'core:index' %}" class="header item">
            <img src="https://image.flaticon.com/icons/svg/1901/1901742.svg" class="image"> Bet Admin
        </a>

        <div class="right menu">

            <div class="ui simple dropdown item">
                <img src="https://image.flaticon.com/icons/svg/118/118781.svg" class="img-container"> {{ user }}
                <div class="menu">
                    <a class="item" href="{% url 'accounts:profile' %}">Perfil</a>
                    <a class="item" href="{% url 'accounts:logout' %}">Sair</a>
                </div>
            </div>
        </div>

    </div>
</div>
{% if not user.profile.email_confirmed %}
<div class="ui warning message" style="margin-top: -14px !important">
    <div class="ui container center aligned">
        <i class="inbox icon"></i>
        <strong>
                    Por favor confirme seu email:
                    {{ user.email }}.
                </strong>
        <a href="{% url 'accounts:resend_email' %}">Resend email.</a>
    </div>
</div>
{% endif %} {% if success %}
<div class="ui container center">
    <div class="ui floating success message">
        <i class="close icon"></i>
        <div class="header">
            {{success.header}}
        </div>
        <p>{{success.content}}</p>
    </div>
</div>
{% endif %} {% block page-container %} {% endblock page-container%} {% endblock container%}